name: WAP Release
on:
  release:
    types: [published]

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.IMAGE_NAME }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  CapRover_Deploy:
    needs: [build_and_push_to_registry]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: floms/action-caprover@v1
        with:
          host: ${{ secrets.CAPROVER_SERVER }}
          password: ${{ secrets.CAPROVER_PASSWORD }}
          app: "wap"
          image: ${{ vars.IMAGE_NAME }}