name: Update Centralized Repository
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  updata_centralized_repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Centralized repository
        env:
          PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
          PAT_EMAIL: ${{ secrets.PAT_EMAIL }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
        run: |
          REPO_PATH=`pwd`
          git pull
          git clone https://$PAT_USERNAME:$PAT_TOKEN@github.com/ada-pld/$REPOSITORY ../$REPOSITORY
          cd ../$REPOSITORY
          git remote add public file://$REPO_PATH
          git pull public main

          git config user.name "$PAT_USERNAME"
          git config user.email "$PAT_EMAIL"

          git add .
          git commit -m "[Automated] Update to commit $GITHUB_SHA"
          git tag last_update_from_public

          git push --set-upstream origin update-to-$GITHUB_SHA

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
        run: gh pr create -R "ada-pld/$REPOSITORY" -B main -H "update-to-$GITHUB_SHA" -b "[Automated] Update to commit $GITHUB_SHA" -t "Automated pull request to update repository to $GITHUB_SHA"